package FRAMES;
import javax.swing.*;
import java.awt.event.*;
import java.util.regex.*;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Medac
 */
public class JFrameVentana extends javax.swing.JFrame {

    /**
     * Creates new form JFrameVentana
     */
    public JFrameVentana() {
        initComponents();
        
        
          //Doy iamgen a mi  barra de tareas, y doy nombre 
       setIconImage(new ImageIcon(getClass().getResource("/Imágenes/LOGO.png")).getImage());
       setTitle("Busly APP");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextoPassword = new javax.swing.JLabel();
        BotonLogin = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        EmailField = new javax.swing.JTextField();
        TextoLogin1 = new javax.swing.JLabel();
        TextoEmail = new javax.swing.JLabel();
        LabelDeFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoPassword.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        TextoPassword.setForeground(new java.awt.Color(153, 153, 153));
        TextoPassword.setText("Password");
        jPanel1.add(TextoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        BotonLogin.setBackground(new java.awt.Color(238, 55, 55));
        BotonLogin.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        BotonLogin.setForeground(new java.awt.Color(255, 255, 255));
        BotonLogin.setText("Login");
        BotonLogin.setBorder(null);
        BotonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BotonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 110, 30));

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 250, 30));

        EmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFieldFocusLost(evt);
            }
        });
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });
        EmailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailFieldKeyTyped(evt);
            }
        });
        jPanel1.add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 250, 30));

        TextoLogin1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        TextoLogin1.setForeground(new java.awt.Color(238, 55, 55));
        TextoLogin1.setText("Login");
        jPanel1.add(TextoLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        TextoEmail.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        TextoEmail.setForeground(new java.awt.Color(153, 153, 153));
        TextoEmail.setText("Email");
        jPanel1.add(TextoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        LabelDeFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/JFRAME.jpg"))); // NOI18N
        jPanel1.add(LabelDeFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -12, -1, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        
        
        
        
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void EmailFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldKeyTyped

    private void EmailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFieldFocusLost
      String inputEmail = EmailField.getText(); // TODO add your handling code here: String inputEmail = jTextField1.getText();
    String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
    
    if (!inputEmail.matches(emailRegex)) {
        JOptionPane.showMessageDialog(this, "Por favor, introduce un email válido.", "Error de validación", JOptionPane.ERROR_MESSAGE);
        EmailField.requestFocus();  // Devuelve el foco al JTextField
    }
    }//GEN-LAST:event_EmailFieldFocusLost

    private void BotonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLoginActionPerformed

 String inputEmail = EmailField.getText();
    String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
    
    // Obtener la contraseña ingresada
    String inputPassword = new String(PasswordField.getPassword()); // Obtiene la contraseña de  JPasswordField

    // Validar el email
    if (inputEmail.matches(emailRegex)) {
        // Validar la contraseña
        if (inputPassword.equals("12345678")) { 
        // Comprueba si la contraseña es "12345678"
        // Mostrar mensaje de bienvenida
            JOptionPane.showMessageDialog(this, "¡Bienvenido a BUSLY! Nos encanta tenerte de vuelta", "Bienvenid@", JOptionPane.INFORMATION_MESSAGE);
        // Crear un SwingWorker para abrir JFrameAbono después de un retraso
            new SwingWorker<Void, Void>() {
                @Override
                protected Void doInBackground() throws Exception {
                    Thread.sleep(500); // Retraso de 0.5 segundos
                    return null;
                }

                @Override
                protected void done() {
                    // Abre la nueva ventana
                    JFrameAbono abonoFrame = new JFrameAbono();
                    abonoFrame.setVisible(true); //Hago visible mi JFrame para que aparezca el nuevo en pantalla
                    dispose(); // Cierra la ventana actual
                }
            }.execute();

        } else {
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta. Intente nuevamente.", "Error de validación", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, introduce un email válido.", "Error de validación", JOptionPane.ERROR_MESSAGE);
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_BotonLoginActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new JFrameVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLogin;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel LabelDeFoto;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel TextoEmail;
    private javax.swing.JLabel TextoLogin1;
    private javax.swing.JLabel TextoPassword;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
