/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRAMES;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Josema
 */

public class JFrameAbono extends javax.swing.JFrame {
    
    //SALDO ACTUAL EN MI LABELSALDO
    
    private double saldoActual = 10.0;
    private JLabel welcomeLabel;

    /**
     * Creates new form JFrameAbono
     */
    public JFrameAbono() {
        initComponents();
        
        
      

       //Doy iamgen a mi  barra de tareas, y doy nombre 
       setIconImage(new ImageIcon(getClass().getResource("/Imágenes/LOGO.png")).getImage());
        setTitle("Busly APP");
        
        
         jMonthChooser1.setVisible(false);
         
          actualizarSaldo();
          
          
    }
     //Método para actualizar el Label con el Saldo Actual
    private void actualizarSaldo() {
        LabelSaldo.setText("Saldo: " + saldoActual + "€");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        LabelSaldo = new javax.swing.JLabel();
        BotonRecarga = new javax.swing.JButton();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(667, 767));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "25", "50", "Abono Mensual", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 280, 50));

        LabelSaldo.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        LabelSaldo.setForeground(new java.awt.Color(238, 55, 55));
        LabelSaldo.setText("     10.0");
        getContentPane().add(LabelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 330, 70));

        BotonRecarga.setBackground(new java.awt.Color(238, 55, 55));
        BotonRecarga.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        BotonRecarga.setForeground(new java.awt.Color(255, 255, 255));
        BotonRecarga.setText("Recargar Saldo");
        BotonRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRecargaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRecarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 260, 60));

        jMonthChooser1.setBackground(new java.awt.Color(238, 55, 55));
        jMonthChooser1.setForeground(new java.awt.Color(255, 255, 255));
        jMonthChooser1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jMonthChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 140, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/JFRAMEABONOI3.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

                                                 
    String seleccion = (String) jComboBox1.getSelectedItem();
    if ("Abono Mensual".equals(seleccion)) {
        jMonthChooser1.setVisible(true); // Mostrar el JMonthChooser
    } else {
        jMonthChooser1.setVisible(false); // Ocultar el JMonthChooser
    }
        //Lógica con la que manejo las acciones del ComboBox y Recargar el saldo
               
        if (seleccion.equals("5€")) {
            saldoActual += 5;
        } else if (seleccion.equals("10€")) {
            saldoActual += 10;
        } else if (seleccion.equals("25€")) {
            saldoActual += 25;
        } else if (seleccion.equals("50€")) {
            saldoActual += 50;
        } 
        
         actualizarSaldo();
        
   
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BotonRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRecargaActionPerformed
  String seleccion = (String) jComboBox1.getSelectedItem();
    double recarga = 0.0;

    if (seleccion == null) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una opción de recarga.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    switch (seleccion) {
        case "5":
            recarga = 5.0;
            break;
        case "10":
            recarga = 10.0;
            break;
        case "25":
            recarga = 25.0;
            break;
        case "50":
            recarga = 50.0;
            break;
        case "Abono Mensual":
            recarga = 100.0;
            // Verifica que se haya seleccionado un mes
            int mesSeleccionado = jMonthChooser1.getMonth() + 1; // Los meses van de 0 a 11
            if (mesSeleccionado < 1 || mesSeleccionado > 12) {
                JOptionPane.showMessageDialog(this, "Por favor, selecciona un mes válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Abono Mensual para el mes: " + mesSeleccionado + " recargado con éxito.", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
            break;
        default:
            JOptionPane.showMessageDialog(this, "Selecciona una opción válida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
    }

    // Sumar la recarga al saldo actual
    saldoActual += recarga;

    // Actualizar el JLabel con el nuevo saldo
    actualizarSaldo();

    // Mostrar un mensaje de confirmación si no es Abono Mensual
    if (!"Abono Mensual".equals(seleccion)) {
        JOptionPane.showMessageDialog(this, "Recarga de " + recarga + "€ realizada con éxito.", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
    }

    // Reiniciar la selección del JComboBox y ocultar el JMonthChooser
    jComboBox1.setSelectedIndex(-1);
    jMonthChooser1.setVisible(false);






    }//GEN-LAST:event_BotonRecargaActionPerformed
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAbono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRecarga;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel LabelSaldo;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    // End of variables declaration//GEN-END:variables
}
